apiVersion: v1
kind: PersistentVolume
metadata:
  name: mospi-backend-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data/mospi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mospi-backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
