apiVersion: v1
kind: Service
metadata:
  name: mospi-front-website-service
  labels:
    app: mospi-front-website
spec:
  type: NodePort
  selector:
    app: mospi-front-website
  ports:
    - port: 3000           # Service port
      targetPort: 3000      # Container's port
      nodePort: 30010       # External NodePort (in the 30000-32767 range)
