apiVersion: v1
kind: Service
metadata:
  name: mopsi-front-cms
  labels:
    app: mospi-front-cms
spec:
  type: NodePort
  selector:
    app: mospi-front-cms
  ports:
    - port: 3000           # Service port
      targetPort: 3000      # Container's port
      nodePort: 30020       # External NodePort (in the 30000-32767 range)
